GET http://localhost:8000/api/product/products/ HTTP/1.1

###

PUT   http://localhost:8000/api/product/products/7/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYzNDc5NjA4LCJpYXQiOjE3NjM0NzkzMDgsImp0aSI6ImYxMzkxOGFlOGZiYjRkYmJhODU3ODU2ODhlYmI0OTZmIiwidXNlcl9pZCI6IjIifQ.w2Qt8jrPrZl3xMyDN_kgYvHW87Ugw6mFgKOwQNbCRKY
{
    "name": "Coffee Cup (One Time)",
    "description": "Rerum fugiat asperiores amet quae labore accusantium eaque ipsa, provident quod quia quasi tempore ut rem dicta ipsum? Cum aspernatur fuga nesciunt.",
    "price": "10.99",
    "stock": 3
}


###

POST http://localhost:8000/api/product/products/
Header {
    "Content-Type": "application/json",
    "Authorization": Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYzNDc5NjA4LCJpYXQiOjE3NjM0NzkzMDgsImp0aSI6ImYxMzkxOGFlOGZiYjRkYmJhODU3ODU2ODhlYmI0OTZmIiwidXNlcl9pZCI6IjIifQ.w2Qt8jrPrZl3xMyDN_kgYvHW87Ugw6mFgKOwQNbCRKY
}

Content-Type: application/json
{
    "name": "Coffee Cup",
      "description": "Rerum fugiat asperiores amet quae labore accusantium eaque ipsa, provident quod quia quasi tempore ut rem dicta ipsum? Cum aspernatur fuga nesciunt.",
      "price": "10.99",
      "stock": 3
}

###
POST http://localhost:8000/api/token/
Content-Type: application/json

{
    "username": "maxamed",
    "password": "maxamed_123"
}