# Generated by Django 5.2.6 on 2025-10-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_product_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='ime',
        ),
        migrations.AddField(
            model_name='book',
            name='ISBN',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
