# Generated by Django 5.2.6 on 2025-11-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_book_ime_book_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
