# Generated by Django 5.2.6 on 2025-10-23 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='owner',
            new_name='user',
        ),
    ]
