# Generated by Django 5.2.6 on 2025-11-01 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='public',
            new_name='published',
        ),
    ]
